### ISSUE TITLE
Add isort and black

### ISSUE THREAD

**Issue by jasperges** [GaoShanPictures/GAOLIB#1]
Hi,

First of all thanks for this very useful add-on. At some point I also considered to port the Studio Library add-on to Blender, but never gotten around to it. So I'm very glad you did. :slightly_smiling_face: 

When deploying this add-on in our studio, I ran into some minor issues. There were some conflicting things with our pipeline. It wasn't too bad to solve, but when doing so my editor was complaining about styling issues all the time. In my opinion it would be nice to enforce some styling. My personal (and our studio's) preference is automatically running [isort](https://pycqa.github.io/isort/) and [black](https://black.readthedocs.io/en/stable/). For me such simple improvements would make it easier to contribute to the project. Would you be okay with this? Do you have other preferences? I don't mind doing a PR for this. It will be a very intrusive change, but it's only once. If you want I could also add a Github workflow that runs some simple checks on your code. This means that if you push new code or someone does a pull request, it will complain if it doesn't pass those checks.

Please, let me know your thoughts.

**Comment by GaoShanPictures** [comment]
Hello, 
Thanks for your comment and advices. I didn't know about black and isort, I'm glad you told me about it and I will definitely think about it. The suggestion about Github checks is interesting too. For now I have to work on several urgent matters, so I may not improve Gaolib right now, but I add it to my TODO list and I'll look a bit more into it later. How about we talk again then ?
 
Best regards,
Anne

**Comment by GaoShanPictures** [comment]
Hi, 
So I've installed black and isort. It's the first time I use it, I hope I did it all ok. For now I've pushed my changes on the additive_mode branch (one of my WIP branch before I push to main), if everything on this branch it's working fine, I should be merging it to the main branch soon. Thanks for the tips.
Anne
