### ISSUE TITLE
Select ARMATURE object error

### ISSUE THREAD

**Issue by animsuperstar** [GaoShanPictures/GAOLIB#2]
![Capture](https://github.com/GaoShanPictures/GAOLIB/assets/161636049/cfc3a227-4dcf-40b2-aefc-0c0d1ba87482)

hello!
i have been using gaolib for a few months, really enjoying it. i have experienced this problem where i have a rig in a scene selected but i get the error that there is no armature object selected when i try to paste my animation in. any suggestions would be appreciated.

im trying to copy anim from one scene to another, the same rig is being used in both shots. and the same version of blender is being used in both shots.

**Comment by GaoShanPictures** [comment]
Hi ! 
Thanks for your feedback ! I'm not sure I will have the time any time soon to check this out. But does it happen everytime, on every rig you have ? Is there any chance you have selected another object at the same time as the armature ?

**Comment by animsuperstar** [comment]
thanks for your reply. 
it is not for every rig, and i have checked that i only have one object selected.

it seems to happen after my scene is opened first by another artist but im not sure what my co-worker might be doing to effect gaolib's functionality

**Comment by GaoShanPictures** [comment]
Hi ! If it does not occur every time, there is a chance that something is wrong with the asset you are using. It might be difficult for me to fix it without further informations... Is there anything written in the console window when it happens ? A screen shot or anything like that could be helpful. But again, Not sure I could take the time to look into this issue right now ... I'll try to get to it as soon as possible. In the meantime, happy blending ;)

**Comment by freen75** [comment]
Hi, 
Are you in pose mode when it happens?
Gaolib requires you to only have a single armature selected, and for that armature to be in pose mode.
