### ISSUE TITLE
Dependencies dont install.

### ISSUE THREAD

**Issue by lucianomunoz** [GaoShanPictures/GAOLIB#3]
Hey I'm trying to run GAOLIB on Blender 4.2 and the dependencies install button wont work :(

**Comment by freen75** [comment]
Hi Luciano,
Could you please include some details?
Error messages are written to the console.
Window>Toggle System Console

I'm guessing you are on windows, right?
On Windows, dependencies have to be installed with admin privileges.

**Comment by Jelones** [comment]
In my experience, the latest supported blender version is 4.0.2 -- any later than that it feeds the dependency error "Command '['D:\\CREATIVE\\CREATIVE_APPS\\3D\\BLENDER\\stable\\blender-4.2.0-stable.a51f293548ad\\4.2\\python\\bin\\python.exe', '-m', 'pip', 'install', 'PySide2']' returned non-zero exit status 1."

**Comment by GaoShanPictures** [comment]
Hello ! 
Thanks for the feedback ! It seems that PySide2, one of the packages used by Gaolib, has no available version for python 3.11 (used in blender 4.2). So for now, the tool won't be compatible with this version of blender. 
I'll try to update it but don't know when I'll be able to release a new version. 
I keep this issue open until I do !

**Comment by Jelones** [comment]
> Hello ! Thanks for the feedback ! It seems that PySide2, one of the packages used by Gaolib, has no available version for python 3.11 (used in blender 4.2). So for now, the tool won't be compatible with this version of blender. I'll try to update it but don't know when I'll be able to release a new version. I keep this issue open until I do !

Thank you for your incredible work -- blender without an animation library just doesn't feel right... (pls don't make me use the god awful blender pose library again)

**Comment by lucianomunoz** [comment]
Sorry I had missed all these messages that went to my spam, 
but i see you figured it.
thank you!

**Comment by GaoShanPictures** [comment]
Hi ! I've released an update of Gaolib. It should work fine on blender 4.2 now. Please open another issue if there's any problem with it, for now we are not using blender 4.2 so I may have forgotten some little things... 
Fingers crossed ! Hope you'll enjoy it !
Happy Blending
